### ISSUE TITLE
Crash!

### ISSUE THREAD

**Issue by simnalamburt** [servo/rust-cocoa#67]
My [dead-simple application](https://github.com/simnalamburt/glium-practice) which depends on rust-cocoa crashes when I merge c4b1941. You can reproduce the error with https://github.com/simnalamburt/glium-practice/commit/ba2615eba48a4a28e4f72abbf2b176bd673532ea

```
glium-practice[19076:161627] +[NSOpenGLContext initWithFormat_shareContext:]: unrecognized selector sent to class 0x7fff7682a850
```

[Go here](https://gist.github.com/simnalamburt/f2902e156f4d3b5a318b#file-dump1) to see the core dump. Sadly, I failed to print stacktrace.

**Comment by metajack** [comment]
Any chance you can submit a modification of your dead-simple app as a unit test?

**Comment by metajack** [comment]
cc @bjz

**Comment by simnalamburt** [comment]
@metajack I think below would be smallest error reproduction but let me test it first

```rust
extern crate glutin;

fn main() {
    let window = glutin::Window::new().unwrap();
    let mut it = window.wait_events();
    loop { it.next(); }
}
```

**Comment by bvssvni** [comment]
cc me

**Comment by bjz** [comment]
Argh it's all my fault again!

**Comment by bjz** [comment]
The [offending line](https://github.com/servo/rust-cocoa/commit/c4b1941432a43acbf9492aea74629f88a8b2c72c#diff-8550f09508786ee2e01c09c7d4722142R1344) is:

~~~rust
msg_send()(class("NSOpenGLContext"), selector("initWithFormat_shareContext:"), format, shareContext)
~~~

Should be `selector("initWithFormat:shareContext:")`.

Duh.

**Comment by bjz** [comment]
Added a PR.
