### ISSUE TITLE
objc_msgSend_fpret usage is probably wrong

### ISSUE THREAD

**Issue by metajack** [servo/rust-cocoa#77]
https://github.com/servo/rust-cocoa/pull/74 changed a use of objc_msgSend to objc_msgSend_fpret, which the docs say is not needed on x86_64. There are comments in the pull request about an alternate fix. Some background on these functions can also be found here http://sealiesoftware.com/blog/archive/2008/11/16/objc_explain_objc_msgSend_fpret.html

Regardless of what the right fix is, the other methods that return CGFloat should also be updated.

**Comment by SSheldon** [comment]
Fixed by #71, `objc_msgSend_fpret` is no longer used.
